project:
  type: website

website:
  title: "Alonso Astroza"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Contact
        href: contact.qmd
      - icon: github
        href: https://github.com/aastroza
      - icon: twitter
        href: https://twitter.com/aastroza
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


