project:
  type: website

website:
  title: "Alonso Astroza"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Talks
        href: talks.qmd
      - text: Contact
        href: contact.qmd
      - text: Español
        href: spanish.qmd  
      - icon: github
        href: https://github.com/aastroza
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto