project:
  type: website

website:
  title: "Alonso Astroza Tagle"
  site-url: https://www.alonsoastroza.com
  repo-url: https://github.com/aastroza/blog
  repo-actions:
    - source
    - edit
    - issue
  open-graph: true
  navbar:
    title: alonso
    background: light
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Talks
        href: talks.qmd
      - text: Consulting
        href: consulting.qmd
      - text: Español
        href: spanish.qmd  
      - icon: github
        href: https://github.com/aastroza

  page-footer:  
    left: >-
     &#169; 2024 Alonso Astroza &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://github.com/aastroza" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/aastrozacl" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://twitter.com/aastroza" title="Twitter" target="_blank"rel="noopener">{{< fa brands twitter >}}</a>
    right: 
      - text: "Contact"
        aria-label: "Contact Form"
        href: "contact.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
resources:
  - CNAME
execute:
  freeze: auto