project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aastroza
      - icon: twitter
        href: https://twitter.com/aastroza
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


