# AI Consulting: Transforming Data into Business Value

I specialize in creating products that transform **raw data** into **business value**, empowering organizations to **optimize** their operations and services. If you're looking to leverage AI to solve complex problems and drive meaningful results, my skills and experience can help you achieve your goals.

I offer tailored consulting services to address your unique challenges at any stage of your project lifecycle. I'm passionate about building new connections and would be thrilled to explore opportunities to work together. [Let's start a conversation](/contact.qmd) and see how we can create value for your organization.

## A Data-Driven Approach to Success

Our journey begins by clearly defining your business challenge. Next, we identify the stakeholders impacted by this challenge and envision what a successful solution looks like for them. Only then do we consider how AI and data analytics can be applied to achieve your objectives.

This methodical approach ensures we tackle your problem with purpose. By understanding your specific needs and desired outcomes, we can work backwards to determine the necessary data, analyses, and tools required to develop an effective solution. This framework allows us to harness AI to create optimized solutions that deliver tangible business value for you and your stakeholders.

## How I Can Help

I offer consulting services and private training to help you transform raw data into business value at any stage of your AI project lifecycle.

### Your AI Strategy

Your AI strategy describes all of the ways you develop, implement, and utilize large language models (LLMs) in your projects. An effective strategy makes these powerful tools accessible and actionable for the people who need them most.

I can help you make LLMs more accessible and usable for solving problems you care about by:

- Identifying performance issues (cost, quality, speed)
- Optimizing Retrieval-Augmented Generation (RAG)
- Implementing fine-tuning techniques
- Developing effective prompt engineering strategies
- Creating dev tools and infrastructure to help you iterate quickly on LLMs
- Evaluating and selecting appropriate LLM vendors

### Your AI Narrative

Your data-driven narrative describes how you build and share knowledge using AI. A compelling narrative helps you and your stakeholders understand and trust the implications of your models, leading to informed solutions that optimize your operations and services.

I can help you develop data-driven solutions that create business value through:

- Building domain-specific evaluation systems
- Designing and implementing custom evaluation metrics
- Hands-on model optimization
- Creating development tools and infrastructure
- Producing content and writing to communicate best practices and methodologies

## Consulting Services

- Developing or evaluating your AI strategy and narrative.
- Short or long term advisory services.
- Negotiable rates by project and typically billed hourly.

## Private Training

- Developing you or your team's LLM and AI programming skills.
- Single or series of workshops or meetings.
- Negotiable rates by training and typically billed per-session for smaller scope or hourly for larger scope.

## Clients

- [GeoVictoria:](https://www.geovictoria.com) A leading provider of time and attendance management solutions. We are working on VictorIA, a conversational AI for HR.
- [Defontana:](https://www.defontana.com) A comprehensive ERP software provider offering solutions for businesses of all sizes, including modules for accounting, HR, POS, and more. I developed a tool to predict inventory demand.
- [Coopeuch:](https://www.coopeuch.cl/) A leading Chilean savings and credit cooperative offering a range of financial services including loans, investments, and insurance. I trained the data analytics team on machine learning.
- [TRC Recruitme:](https://trcrecruitme.com/) A platform dedicated to connecting job seekers with employers. We are building an LLM-powered recruitment platform from unstructured data.
- [Discolab:](https://www.discolab.cl) Deployed an OpenAI API-based product in production, which efficiently searches, summarizes, and compares constitutional texts. The site attracted over 5,000 users per day.
- [Subconscious.ai:](https://www.subconscious.ai/)  I helped build an AI Copilot for causal market research, leveraging LangChain's [LCEL](https://python.langchain.com/docs/expression_language/) to transform the query process for LLMs.

---

Let's work together to harness the power of AI and solve the problems you care about!

<form action="https://formspree.io/f/mjkbkbkn" method="POST" accept-charset="utf-8">


<label for="full-name">Full Name</label>
<input type="text" name="name" id="full-name" class="form-control" placeholder="First and Last" required>

<label for="email-address">Email Address</label>
<input type="email" name="_replyto" id="email-address" class="form-control" placeholder="your@email.here" required>

<label for="message">Message</label>
  <textarea rows="6" name="message" id="message" class="form-control" placeholder="Hi Alonso!" required></textarea>

<button type="submit" class="btn btn-primary mt-4">Send</button>
</form>