site_name: aastroza
theme:
  icon:
    logo: simple/robotframework
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - navigation.tabs
  font:
    text: Inter
    code: Source Code Pro
nav:
- Home:
  - About Me: index.md
- Generative AI:
  - Acerca del Curso: genai/about.md
  - Bibliografía: genai/bibliografia.md
  - Introducción a la IA Generativa: genai/introduccion.md
  - Generando Texto: genai/texto.md
  - Generando Imágenes: genai/imagenes.md
  - Generando Video: genai/video.md
  - Generando Audio: genai/audio.md
- Data Products:
  - Introduccion: dataproducts/introduccion.md
- AI Pair Programming:
  - Intro: [aicoding/intro.md]
- Esports:
  - Introduccion: esports/introduccion.md
- PowerBI:
  - Video Course: powerbi/introduccion.md
- Blog: 
  - "blog/index.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - social
  - blog:
      blog_dir: "blog"
      blog_toc: true
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<alonsoastroza@gmail.com>
    - icon: fontawesome/brands/github
      link: https://github.com/aastroza
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aastrozacl/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aastroza
  analytics:
    provider: google
    property: G-SKBY5FHZWG

copyright: Copyright &copy; 2023 Alonso Astroza